### ISSUE TITLE
[Bug]: Cannot connect at all on one iPad

### ISSUE THREAD

**Issue by YX42** [streamyfin/streamyfin#314] opened 2024-12-28 00:23 UTC
Update: I successfully connected the iPad now by deleting the app via storage (delete all data) and restarting the device. After reinstalling Streamyfin connecting to the server worked flawlessly.

### What happened?

It won't let me connect to the Jellyfin server. I accidentally entered a wrong URL first (htttp) and nothing happens when I enter the correct one now. It's only on my local iPad. It works fine on another one that connected from far away (Streamyfin, VPN, same URL).
The only difference is that the URL was entered correctly on the first try.
I already deleted the app, reinstalled etc. Nothing has helped so far.
Swiftfin works without issues on the same iPad.

### Reproduction steps

1. Download Streamyfin
2. Start app
3. Enter wrong URL
4. Enter correct URL
5. Nothing happens

### Which device and operating system are you using?

iPad Air, iPadOS 18.2

### Version

0.22.0

**Comment by michaelcresswell** [comment] 2024-12-28 20:13
For what it’s worth, I had an iPad that didn’t want to connect initially but was able to later after not trying for a few days. Don’t remember if I made a typo the first time. 

Jellyfin, Swiftfin, and Finamp all worked with the expected URL the entire time.

**Comment by fredrikburmester** [comment] 2024-12-31 07:57
Is this still an issue?

**Comment by YX42** [comment] 2024-12-31 13:31
I guess it might be for others in the future, but for me personally I was able to fix it. Thank you

**Comment by fredrikburmester** [comment] 2024-12-31 15:33
Thank you i'll close this issue for now. If anyone else has this issue please let me know and i'll reopen.

**Closed by fredrikburmester** 2024-12-31 15:33 UTC
Labels: ❌ bug

**Comment by lutyjj** [comment] 2025-01-04 09:17
I experience this issue on M1 iPad Pro 11’. 

No matter what I do, just nothing happens after clicking “Connect” button.
Tried every combination of the URLs, e.g.:
http://192.168.1.1:8096/
http://192.168.1.1:8096
http://192.168.1.1/
http://192.168.1.1

Tried re-installing the app, no luck either. Still can’t get it to work. Swiftfin works fine.

What’s interesting is that when I enter incorrect URL, at least it reacts to clicking on “Connect” button and the spinner icon appears. Doesn’t happen with correct URL.

**Comment by fredrikburmester** [comment] 2025-01-04 09:30
What version of the app are you using? @lutyjj

**Comment by lutyjj** [comment] 2025-01-04 09:33
Sorry, forgot to mention this!
Version is the latest one from the App Store, 0.22.0.

I was able to login before, but can’t recall which version was it (<0.22.0) - since then I uninstalled and re-installed the app back.

**Comment by fredrikburmester** [comment] 2025-01-04 09:38
Ok strange.. I'm able to log into my iPad. Let's wait for the 0.23.0 release coming in a day or two to see if that solves anything.

**Comment by YX42** [comment] 2025-01-04 11:48
@lutyjj try deinstalling via settings/general/iPad storage "delete all data", then completely turn off your device, then reinstall the app. Additionally I rotated the screen to portrait mode before connecting to the server the time it finally worked.

**Comment by lutyjj** [comment] 2025-01-05 07:33
Update 0.23.0 indeed fixed the issue for me, thanks!
Out of curiosity also tried to reproduce the issue @YX42 originally had with providing incorrect link and correcting it - works fine too now.
